### ISSUE TITLE
Read the Code for America MOU for brigades

### ISSUE THREAD

**Issue by froi** [Code4PuertoRico/Code4PR#12]
Code for America has a MOU which official brigades need to sign to be recognized. While we have been recognized for some time, the MOU has been updated since last we read it.

The stipulation in the MOU will help us figure out our own mission, vision, and value statements. At the same time it will help us determine if we want to stay a recognized brigade.

[CfA Brigade MOU](https://docs.google.com/document/d/1TtEWZ1-XY3WHJ9dU4KaMIjDx7wcFGw3lbM8O8iUt2Sw)

——

Want to comment on this issue? please take a look at issue https://github.com/Code4PuertoRico/Code4PR/issues/17.

**Comment by froi** [comment]
There’s a couple of things that have pooped out to me in the MOU

## A Code for America Brigade is considered a “Brigade”if:

> Does not have independent legal status (eg. non-profit corporation, LLC, partnership)

This really doesn’t leave much to discussion as to what our status would be if we do a legal entity.

> Follows Code for America naming conventions. Is called Code for [X] or Open [X]

We are part of the grandfathered organizations.

## Legal Standing

> The Code for America Brigades are a part of the Code for America organization and as such fall under Code for America 501(c)(3) tax-excempt status __and therefore don’t have legal standing outside of the Code for America organization__.

This solves the “finding a fiscal sponsor” issue. This will help us get financial support immediately through Code for America and their official donation channels.

This will also limit us in what partnerships we can do. Especially if said partnership needs a legal entity to sign off on documents.

> When Brigade leaders and members sign documents such as rental agreements, contracts, invoices, etc., they are signing as individuals

We pretty much knew this off the bat. 

> If the Brigade needs a Code for America authorized signature, contact ​brigade-info@codeforamerica.org​.

I wonder if an organization like the PR Science Trust want to sign a MOU with us, if this is a case that would need their signature?

**Comment by froi** [comment]
## Brigade Leadership

> Each Brigade must designate one of their Brigade Captains as the primary contact for Code of America’s staff.

First I don’t want to use terms like _captain_, I prefer leader or chair. A captain is somebody that barks orders with the expectation that people will follow them without question. I think that is counter to what we want to build.

It also implies that there is higher ranking individuals that can override and even remove _captains_. Communities have leaders and our vocabulary should reflect that.

**Comment by froi** [comment]
## Code for America agrees to provide

### Events and visibility

> 1. Access to the Code for America Summit with 2 “pay what you can” entrance tickets for primary days.

This a great opportunity for those that would wish to go to the summit. It also let’s us focus on getting funds for financial assistance to brigade members that wish to attend.

> 2. Annual Brigade Congress open to all Brigade members.

This is just good networking.

> 4. Visibility through Code for America’s social media and web properties,

This helps solve the biggest issue we’ve had over the years, promo and marketing. Having an organization like CfA include us in their digital presence can hugely boost our “standing” with other orgs and partners.

> 5. Highlighting Brigades, their leaders, and success stories through media outreach, at events, etc

This could provide excellent exposure and career boosts to current and future leaders.

### Administrative and fiscal management

> so that individual brigades have a base of infrastructure to start from.

This was missing when we started in 2014. At least it was not properly defined. What would this mean for us today?

> Because Brigades do not function as a separate legal entity, each Brigade will rely on a non-profit organization to accept and manage these donations.

This was already known but having it in the MOU might tell us that CfA could help us figure all this out.

There are two options for brigades when it comes to this topic:

1. Code for America handles all financial administration (the majority of cases fall here)
2. Brigades have a local fiscal sponsor

Let’s go over these one at a time.

**Comment by froi** [comment]
## Code for America handles all financial administration (the majority of cases fall here)

This was the model that existed when we were founded in 2014.

> This is a model for financial support for the Brigade in which funds raised by the Brigade members from donors will be accepted and managed by Code for America.

This give us the opportunity to not focus on “legal fiscal responsibility” and keeping the books clean. This can be a huge boon, especially in a small team.

I wonder if in this model there is a space for us to sign paid MOUs and pay people for their contribution by submitting the invoice through CfA. Similar to submitting expenses through Expensify.

I think this is a great help to start off running and not expose the leadership team to possible tax issues. 

An important note, though nto surprising, is that funds need to be raised by brigade members. CfA does not give monetary support to the brigade’s fund.

> Use of Code for America’s donation platforms

This answers partially answers my question above.

> Use of Code for America’s expense reporting systems so that members can be __reimbursed__ for expenses incurred form managing their group.

Having this be a reimbursement is an important consideration. While I understand why this is the way it is, even prefer it, this might limit future leaders. Not everybody has disposable income and can wait for a reimbursement.

 Can paying contributors be considered a _cost of managing their group?

> Relationship letter stating Code for America’s 501c3 status.

This will be necessary to reassure donors about where the money is headed and that they are tax deductible.

> Applications for travel support to Code for America events where available

This is huge, especially for members that are in PR. I wonder if as a brigade we could also fund raise to help our members participate? 🤔

**Comment by froi** [comment]
## What CfA offers - Fiscal Management

### Brigade with local sponsors

Our financials would be managed by another legal entity (other than CfA).

IMHO, the only real advantage to this being associated to a local non-profit that has some local clout. 

For example, people back home know and trust Foundations for Puerto Rico.

> Use of Code for America’s donation platforms

Being able to keep using a donation platform is huge! This will alíviate the burden of looking for, joining, and trusting other platforms.

> Transfer to the third party fiscal sponsor all the net funds raised for the Brigade
via Code for America’s donation platform.

This is great. As I understand it this inquires no extra cost and is done so automatically.

There just needs to be some coordination with the fiscal sponsor on how to link their account.

> The Brigade must send a relationship letter from fiscal sponsor stating their 501c3 status and relationship with the Brigade.

Even if this were not needed we would still need the letter to show other donor / organizations. Totally understandable.

> Applications for travel support to Code for America events where available

Not much more to say except cool.

**Comment by froi** [comment]
## What CfA offers - Free and discounted tools

CfA has a number of sponsors and partners that make their services / tools available to us as an official Brigade.

For example:

- Our Google Apps acounts (email, drive, etc)
- CartoDB
- Mapbox
- Slack

[See the full list](http://brigade.codeforamerica.org/resources/software)

Historically we have not done a good job in using this.

**Comment by froi** [comment]
## What CfA offers - a moderated community for dialogue and dot connecting

> Facilitation of relationship-building between members of our network through shared directories and newsletters.

The CfA / brigade network is amazing. This is a huge plus for us, especially since PR is often times very much removed / overlooked.

> Opportunities to participate in the governance of the Brigade Network.

Same as above, having the opportunity to impact the Brigade Network at a national level can provide great leadership opportunities to members that might otherwise never get them.

> An accessible process for voting in the National Advisory Election and any other elected positions that become available.

Providing our members the opportunity to elect the people that impact their participation in the brigade and the opportunities to see their projects succeed is a big plus.

> Process by which members can run for National Advisory Council positions.

Gives leadership opportunities that were previously not available to some of our members.

**Comment by froi** [comment]
## What the Brigade agrees to

> Provide Code for America Brigade members’ contact information

Why and is there space for our members to not give their contact information to us and third parties?

> Build and maintain a respectful and productive relationship with municipal partners and local government.

The way Code 4 PR is structured makes this a bit difficult. We are a totally remote org that doesn’t have hack-nights (we don’t plan to either). We do not have a “local” presence in any municipality (at the moment). 

This could just be a formality but I think need to clear this up. Up to now we do not have an adversarial relationship with any government entity in PR.

Most of our efforts have also been focused at the national level. We had one interaction with the San Juan city government years ago, but that relationship was not 100% fruitful or stable.

I think that as a brigade we need to start thinking of impacting local communities more. Then maybe this will be easier for us.

> Recognize Code for America on materials, websites, and in communications

Simple enough and understandable.

> Follow the Code for America brand standards and messaging guidelines.

We need to read these and determine if they make sense in PR. For obvious reasons the CfA messaging is EEUU focused.

There are a lot of EEUU companies that needed to change their messaging and outreach when opening shop in PR.  I think some good old fashioned user research is needed to determine what this will mean for us and if it complies with CfA guidelines.

I wonder if they are aware of this and if there is any room for exceptions and changes?

> Abide by Code for America’s administrative and fiscal management guidelines
and decisions.

What are these and how will they impact our day to day in managing Code4PR?

**Comment by froi** [comment]
While the MOU stipulates that no brigade should be it's out legal entity, there are a couple of brigades that have gone down this journey:

- Hack for LA
- Code for Miami
- BetaNYC
- Kansas City ( I think )

[There's a great discussion on the topic](https://discourse.codeforamerica.org/t/brigade-business-models/704) on the CfA Dicsourse.

**Comment by albertico** [comment]
@albertico's notes/comments on the [CfA Brigade MOU](https://docs.google.com/document/d/1TtEWZ1-XY3WHJ9dU4KaMIjDx7wcFGw3lbM8O8iUt2Sw):

# Introduction

> A Code for America Brigade is considered a “Brigade” if it:
>
> 1.  Has an up-to-date signed MOU with Code for America; and
>
>2.  Does not have independent legal status (eg: non-profit corporation, LLC, partnership)

This seems as if any type of incorporation will remove the possibility of the organization being recognized as a "Brigade" and becoming part of the Brigade Network.

> 3.  Follows Code for America naming conventions. Is called Code for [X] or Open [X].

Code 4 Puerto Rico is definitely under the grandfathered model. Unclear how much openness would there be for a potential name change, if so was decided.

> 4.  Has a designated Brigade leader, typically called a Captain

Seems that CfA only requires a point of contact (and an alternate). I don't interpret this as requiring or forcing a specific organizing structure. Brigades could still self-organize and define a structure beyond the captain/co-captain model. Nice example is OpenOakland.

---

# Memorandum of Understanding

> This Memorandum of Understanding between CFA and the Brigade will go into effect on [date] and remain in effect until the pilot period ends on June 30, 2018. If no substantial changes are recommended by Code for America or the National Advisory Council on behalf of the Brigades, the term will be extended until December 31, 2018.

Unclear if this MOU model is still valid in 2020.

---

# Legal Standing

> The Code for America Brigades are a part of the Code for America organization and as such fall under Code for America’s 501(c)(3) tax-exempt status, and therefore don’t have legal standing outside of the Code for America organization. When Brigade leaders and members sign documents such as rental agreements, contracts, invoices etc.., they are signing as individuals, not as a representative of Code for America.  If the Brigade needs a Code for America authorized signature, contact brigade-info@codeforamerica.org.

There is some overhead and bureaucracy involved here. I doesn't seem clear if there are any costs/charges that CfA would make to the Brigade if they were to act as their fiscal sponsor.

---

# Brigade Leadership (A)

> I. Code for America agrees to provide:
>
> A. Events and visibility which connect individual efforts such that the Brigades together make-up a movement:
>
>     I. Access to the Code for America Summit with 2 “pay what you can” entrance tickets for primary days.
>     II. Annual Brigade Congress open to all Brigade members.
>     III. Use of Code for America brand within our branding guidelines; including marketing materials,
>     IV. Visibility through Code for America’s social media and web properties,
>     V. Highlighting Brigades, their leaders, and success stories through media outreach, at events, etc.

In general, these are pretty nice benefits that we would get from becoming an official "Brigade".  That said, it remains unclear whether there are any other ways to get access and participate in some of these if we had some kind of legal status.

I see a lot of value in:

> I. Access to the Code for America Summit with 2 “pay what you can” entrance tickets for primary days.

The more brigade members that could participate in the Summit, the better. This would definitely help towards that.

> II. Annual Brigade Congress open to all Brigade members.

Brigade Congress is a great mechanism to engage with other brigades and partners. It would be very sad if incorporating C4PR would remove the possibility to participate.

> IV. Visibility through Code for America’s social media and web properties
> V. Highlighting Brigades, their leaders, and success stories through media outreach, at events, etc.

Having CfA help us reach more people, show our work and amplify our outreach mechanisms could be very helpful.

I see less value in:

> III. Use of Code for America brand within our branding guidelines; including marketing materials

These are english based and US-centric artifacts that don't necessarily work for the Puerto Rico audience.

---

# Brigade Leadership (B)

> I. Code for America agrees to provide:
>
> B. Administrative and fiscal management so that individual brigades have a base of infrastructure to start from. Brigade members may need financial support for their work. Because Brigades do not function as a separate legal entity, each Brigade will rely on a non-profit organization to accept and manage these donations.
>
> To Brigades with Code for America handling financial administration: (the majority of cases)
> _This is a model for financial support for the Brigade in which funds raised by the Brigade members from donors will be accepted and managed by Code for America._
> I. Use of Code for America’s donation platforms.
> II. Use of Code for America’s expense reporting systems so that members can be reimbursed for expenses incurred from managing their group.
> III. Relationship letter stating Code for America’s 501c3 status.
> IV. Applications for travel support to Code for America events where available.
> V. If the Brigade needs a Code for America authorized signature, contact brigade-info@codeforamerica.org.
>
> To Brigades with a local fiscal sponsor,
> _This is a model for financial support in which the funds are managed by another non-profit entity (other than Code for America) that accepts and manages funds provided by donors._
> VI. Use of Code for America’s donation platforms.
> VII. Transfer to the third party fiscal sponsor all the net funds raised for the Brigade via Code for America’s donation platform. 
> VIII. The Brigade must send a relationship letter from fiscal sponsor stating their 501c3 status and relationship with the Brigade.
> IX. Applications for travel support to Code for America events where available.

It is unclear to me whether these two options are mutually exclusive. Is a Brigade allowed to have more than one fiscal sponsor, one being CfA, and still be recognized as a Brigade? Can a Brigade distribute/negotiate these responsibilities between more than one fiscal sponsor?

---

# Brigade Leadership (C)

> C. Free and discounted tools so that projects can be completed with little or no cost.
>   I. Access to in-kind services from supporting sponsors; including Code for America’s Meetup Pro instance.

These tools being available is really nice. Although many of the companies listed have programs/discounts for non-profits, we would need to take the burden of managing and applying to each of them individually if we were to take the 501(c)3 route ourselves.

---

# Brigade Leadership (D)

> D. A moderated community for dialogue and dot connecting.
>   I. Facilitation of relationship-building between members of our network through shared directories and newsletters.
>   II. Access to Code for America’s network on Slack.
>   III. Opportunities to participate in the governance of the Brigade Network.
>   IV. An accessible process for voting in the National Advisory Election and any other elected positions that become available.
>   V. Process by which members can run for National Advisory Council positions.

I see a lot of value in participating on the National Advisory Council and being part of the network. Some of these feel a little geographically specific. C4PR is aiming to be a distributed organization, so some of these relationships and interactions may look different and may expand beyond Puerto Rico. Being part of the Council could be a way for C4PR to contribute framing the conversation beyond a state centric model. C4PR could also be a voice for other territories so that the network accounts for them. That said, we should first agree that this is something we consider aligned with our mision/vision/goals/values.

**Comment by froi** [comment]
# Conclusions

1. We are going to stay in CfA as an official brigade for now pending a review of the new MOU that is going to be released.
    1. We do not have a release date
1. We will ask if having multiple fiscal sponsors is posible
    1. There are laws that might prevent us from getting funds from NGOs registered in PR through an entity that is not registered on the island (CfA).
1. We need to establish a board regardless of our status with CfA or without CfA.
1. We need to get more information about the CfA National Advisory Council.
1. We need to get more information about the CfA brigade congress
