### ISSUE TITLE
Should we join Code for All

### ISSUE THREAD

**Issue by froi** [Code4PuertoRico/Code4PR#18]
[Code for All](https://codeforall.org/) is an international organization of civic minded orgs that are not a part of Code for America.

I've been participating in this org for a while and they have interacted and promoted our content on Twitter and other platforms.

My experience with them has been amazing. They are very welcoming and tackle a series of issues that affect local and international communities.

Here's what I would like to discuss in this issue:

1. Should we as Code for Puerto Rico join Code for All?
    1. What would that process be like?
1. What would it mean for our relationship with Code for America?
1. Can we be a part of both at the same time?
    1. Would it be better to join this org and then start working on being a 501c3?
1. Is there a bigger benefit for our members to be a part of Code for All?

**Comment by albertico** [comment]
# Code 4 Puerto Rico and Code for All

Maintaining and cultivating our relationship is a valuable for Code 4 Puerto Rico, given our political status (unincorporated territory) and our hispanic ethnicity. There doesn't seem to be anything stopping us from being a CfA recognized Brigade and continue to participate in Code for All. The issues they tackle and the diversity of their community are also important values for us.

@albertico thinks we should maintain our participation in Code for All.

**Comment by froi** [comment]
> Maintaining and cultivating our relationship is a valuable for Code 4 Puerto Rico, given our political status (unincorporated territory) and our hispanic ethnicity. There doesn't seem to be anything stopping us from being a CfA recognized Brigade and continue to participate in Code for All. The issues they tackle and the diversity of their community are also important values for us.
> 
> @albertico thinks we should maintain our participation in Code for All.

Agreed.1 🎉

**Comment by froi** [comment]
I've reached out to Code for All during their summit. They are going to get back to us on what would the process be and even if we could.

Code for America is already a part of Code for All and as such we would "already be a part of it".

**Comment by froi** [comment]
For now this will be on hold. Being a part of CfA covers all of what we need for now. CfA is also a member of Code for All.

If we ever break from CfA by establishing ourselves as a legal entity we can take this back up.
