### ISSUE TITLE
Terremoto Puerto Rico 2020 community efforts

### ISSUE THREAD

**Issue by froi** [Code4PuertoRico/Code4PR#2]
Si saben de un esfuerzo de la comunidad de tech en PR para trabajar con los afectados de los sismos en Puerto Rico del 2020, por favor añadalo aqui como un comentario.

Informacion importante

```
¿Que es?  Mapa de refugios

URL: https://algo-de-mapas

De donde viene la data: 

Comentarios:

Comentarios aqui.
```

**Comment by froi** [comment]
¿Que es? Mapa de refugios

URL: https://pr-quake.hurricane-response.org/

De donde viene la data: No se. Estoy verificando

Comentarios: 

Esto lo publico Code for America. Aparentan estar asociados con https://www.prvoad.org/ de alguna manera. No estoy 100% seguro.

**Comment by albertico** [comment]
**¿Qué es?** Mapa de Refugios

**URL:** https://batchgeo.com/map/d487cd55764a9fe3f13ff4959b8ee93f

**De donde viene la data:** Desconocido

**Comentarios:**

**Comment by albertico** [comment]
**¿Qué es?** API que convierte los datos del [Mapa de Refugios](https://github.com/Code4PuertoRico/Code4PR/issues/2#issuecomment-573363535) de formato KML a JSON

**URL:** https://github.com/gcollazo/sos-sur

**De donde viene la data:** Del Mapa de Refugios: https://batchgeo.com/map/kml/de8ab2455315ad6fa4b05522d88c3ed6 (formato KML)

**Comentarios:** Desarrollado por [@gcollazo](https://github.com/gcollazo).

**Comment by albertico** [comment]
**¿Qué es?** API con datos de refugios provisto por FEMA

**URL:**

- JSON: https://gis.fema.gov/arcgis/rest/services/NSS/OpenShelters/MapServer/0/query?where=STATE=%27PR%27&f=json
- GeoJSON: https://gis.fema.gov/arcgis/rest/services/NSS/OpenShelters/MapServer/0/query?where=STATE=%27PR%27&f=geojson

**De donde viene la data:** FEMA (ArcGIS Server)

**Comentarios:** Refugios abiertos.

**Comment by albertico** [comment]
**¿Qué es?** Glitch Project con actualizaciones de Twitter de los Oasis publicados por Acueductos

**URL:** https://oasis-acueductospr.glitch.me/

**De donde viene la data:** Cuenta de Twitter de la Autoridad de Acueductos y Alcantarillados (https://twitter.com/ACUEDUCTOSPR). Principalmente imágenes contenidas en mensajes de twitter.

**Comentarios:** Desarrollado por [@jpadilla](https://github.com/jpadilla) (Github) y [@coral_negron](https://twitter.com/coral_negron) (Twitter)

**Comment by Xiomara7** [comment]
**¿Qué es?** Google doc para centralizar información sobre diferentes iniciativas. Este documento está dividido por fundaciones y recolectas, fundraisers de individuos que perdieron sus hogares, actividades de recaudación de fondos y recursos informativos.

**URL:** [Google Doc en Español](https://docs.google.com/document/d/1jbtBKVSKoi9lTEuxGJh4eQ2q5eMiHdUMu1o33bGNC-4/mobilebasic), [Google Doc en Inglés](https://docs.google.com/document/d/1VE61j7xHmVgiVQMW1FhqR3ZxVgi__YonTNDmPjiUS7w/edit?usp=sharing)

**De dónde viene la data:** Crowdsourced, mayormente en twitter. 

**Comentarios:** Organizado por Cecilia Pou (email: cecipou@gmail.com, twitter: [@cec111a](http://twitter.com/@cec111a)) y Alina Amador (twitter: [@alinin_sin_fin](https://twitter.com/@alinin_sin_fin))

**Comment by froi** [comment]
**¿Qué es?** Portal para que facilita ayuda comunitaria por las propias comunidades.

**URL:** https://www.misnecesidades.org/

**De dónde viene la data:** Crowdsourced, usuarios de la pagina. 

**Comentarios:**

**Comment by abdyelg** [comment]
> **¿Que es?** Mapa de refugios
> 
> **URL:** https://pr-quake.hurricane-response.org/
> 
> **De donde viene la data:** No se. Estoy verificando
> 
> **Comentarios:**
> 
> Esto lo publico Code for America. Aparentan estar asociados con https://www.prvoad.org/ de alguna manera. No estoy 100% seguro.

FYI. Durante el dia de hoy 11 de enero del 2020 baje al área sur y pude ver en Waze muchos de los refugios marcados.

**Comment by froi** [comment]
**¿Qué es?** PR Needs Cash - Website built by [Miguel Rios](https://github.com/miguelrios) to help people donate to organizations working with the relief efforts on the ground.

**URL** [https://www.prneeds.cash/](https://www.prneeds.cash/)

**De donde viene la data:** Manualmente añadida

**Comentarios**

Este projecto es open source. Pueden ver el código aquí [https://github.com/miguelrios/prneeds.cash](https://github.com/miguelrios/prneeds.cash).

**Comment by ella24** [comment]
¿Qué es? Oasis locations throughout the island

URL https://oasis-acueductospr.glitch.me/

De donde viene la data: https://twitter.com/ACUEDUCTOSPR?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1216004444233572352&ref_url=https%3A%2F%2Foasis-acueductospr.glitch.me%2F

Comentarios

Este proyecto está alimentando un spreadsheet constantemente   https://docs.google.com/spreadsheets/d/16QPDusgx-Vp5ZKJvmOBBQ9xXNLVo5Dg5TQCav2xq3hQ/edit#gid=0

**Comment by Xiomara7** [comment]
**¿Qué es?** Page that displays magnitude of the earthquakes vs time. 

**URL:** http://ccom.uprrp.edu/~humberto/temblores/

**Data:** Queries USGS live for most recent data.

Comentarios: Creado por @humberto-ortiz, twitter: [@hortizzuazaga](https://twitter.com/hortizzuazaga)

**Comment by Xiomara7** [comment]
**¿Qué es?** A map of mental health projects that are currently addressing this need. 

**URL:** [Map](https://www.google.com/maps/d/u/0/viewer?mid=1qDtuQPpmtyQCQA6EcBVl1--k5KPAUVxT&hl=en_US&fbclid=IwAR3Jh1_tUGShYXKQ4F1-Z6M3tTFAstOVYYMyzSDWN-BmOi378_1la7BAWrk&ll=18.22001066336684%2C-66.60204914492948&z=9)

**Data . Comments:** Not sure, George Torres shared it on [his LinkedIn](https://www.linkedin.com/in/sofritomediagroup/)

**Comment by froi** [comment]
Gracias @Xiomara7 @ella24 @abdyelg @albertico por aportar a este issue. Lo estaré cerrando por falta de movimiento.
