### ISSUE TITLE
Read CfA's financial administration guide

### ISSUE THREAD

**Issue by froi** [Code4PuertoRico/Code4PR#21]
The guide can be found at http://brigade.codeforamerica.org/resources/financial-administration

**Comment by froi** [comment]
After reading the doc we are in agreement that the best course of action is for us to stay within the CfA structure. We will use them as fiscal sponsors for donations and will explore local fiscal sponsorships as opportunities or legal requirements arise.

CC/ @albertico

**Comment by albertico** [comment]
@froi Agreed! 👍
