### ISSUE TITLE
Measure our options / what do we want to be - public comments

### ISSUE THREAD

**Issue by froi** [Code4PuertoRico/Code4PR#27]
Hola 👋 

Este issue es un lugar para comentarios públicos referente al issue #13.

Por favor mantenga respeto hacia la comunidad. Comentarios que violen nuestro [Código de Conducta](https://github.com/Code4PuertoRico/codeofconduct) serán removidos.

Si no se sienten comod@s en escribir un comentario publico pueden enviarnos un correo electrónico a social@code4puertorico.org

Para cualquier violación de nuestro [Código de Conducta](https://github.com/Code4PuertoRico/codeofconduct) por favor comuníquese a coc@code4puertorico.org.

Gracias!

——

Hi 👋 

This issue is where we are accepting public community comments for issue #13.

Please be respectful to the community. Comments that break our [Code of Conduct](https://github.com/Code4PuertoRico/codeofconduct) will be removed.

If you don’t feel comfortable writing a public comment you can send them in @ social@code4puertorico.org.

For any [Code of Conduct](https://github.com/Code4PuertoRico/codeofconduct) violations please send us an email to coc@code4puertorico.org

Thanks!

**Comment by LaysCurbelo** [comment]
Saludos

Una opción que pueden tomar en consideración es que code4pr se convierta en una corporación B, segun estipulado en:

http://www.lexjuris.com/lexlex/Leyes2015/lexl2015233.htm

Una Corporación de Beneficio Social es una corporación con fines de lucro, que puede emitir valores y acciones de capital, organizada bajo los requisitos de este Capítulo cuya misión y propósitos están dirigidos a fomentar el beneficio público general.

Esta basado en 4 principios:

1. Primacía del fin social, que se concreta en gestión autónoma y transparente, que conlleva priorizar la toma de decisiones en función de las personas y sus aportaciones de trabajo y servicios prestados a la entidad;

2.  Aplicación de los resultados obtenidos de la actividad económica de manera que contribuya a la consecución del fin social de la Corporación;

3. Promoción de la solidaridad dentro de la corporación  y con la sociedad que favorezca el compromiso con el desarrollo local, la igualdad de oportunidades, la cohesión social y la integración de grupos marginados en la comunidad; y

4. Autonomía del Estado sin menoscabar el poder regulatorio que ostenta.

Es una modelo de organización disponible para poder manejar y recibir fondos de una manera más flexible aun teniendo como norte la acción social y la importancia de la base de acción civica.

**Comment by froi** [comment]
@LaysCurbelo Gracias por el feedback. Como hablamos, hemos decidido quedarnos con Code for America como fiscal sponsor. Esto podria cambiar en el futuro pero creemos que por el momento nos ayudaria arrancar en una buena decision.
