### ISSUE TITLE
Retroalimentación de los valores para Code for PR

### ISSUE THREAD

**Issue by froi** [Code4PuertoRico/Code4PR#38]
Como toda organización nuestro norte esta dictado por nuestros valores. Aunque esto valores los vivimos y nos dirigen en nuestros proyectos, es necesario tenerlos escritos. Es importante para nosotros que estos valores sean compatibles con nuestra comunidad. 

Por favor tomen un tiempo para leer los valores que definen a Code for Puerto Rico. Estaremos aceptando retroalimentación hasta el 25 de julio de 2020.

# Nuestros Valores

## Tod@s están bienvenid@s a participar

Para diseñar soluciones que representen a todos, debemos involucrar a personas de todo tipo de  profesiones, credos, orientación sexual, identidad de género y nivel social. Construir soluciones tecnológicas no es solo el trabajo de desarrolladores. Sin importar dónde viva o dónde esté, se puede colaborar virtualmente con nuestras iniciativas, esto es todo lo que necesita para participar.

## Pensamos en personas primero

~Los mejores productos y soluciones no se crean en el vacío. Necesitamos empatía y curiosidad para comprender los problemas, idear soluciones y probar nuestra hipótesis. Debemos evitar hacer suposiciones. Debemos escuchar y comprender a las personas involucradas o afectadas por el problema que pretendemos solucionar. Solo así comenzaremos a crear soluciones que realmente aborden las necesidades de las personas y nuestras comunidades.~

Los mejores productos y soluciones no se crean en el vacío. Necesitamos empatía y curiosidad para comprender los problemas, idear soluciones y probar nuestra hipótesis. Debemos evitar hacer suposiciones. Debemos escuchar y comprender a las personas involucradas o afectadas por el problema que pretendemos solucionar para eliminar nuestros prejuicios. Solo así comenzaremos a crear soluciones menos discriminatorias que realmente aborden las necesidades de las personas y nuestras comunidades.

## Nos esforzamos por construir productos, no publicar código

Las soluciones de impacto son más que código. Nuestra toma de decisiones está fuertemente influenciada por regulaciones, las preocupaciones de las personas afectadas y sus necesidades. No solo estamos empujando código, estamos resolviendo los problemas de las personas a través de experiencias de productos. Cuanto más interdisciplinarios y diversos sean los equipos que trabajan en nuestras iniciativas, más inclusivas serán nuestras soluciones.

## Priorizamos el tener impacto

Las cosas se construyen con una vida útil en mente y eso está bien. Para desarrollar soluciones que sean sostenibles, debemos centrarnos en las cosas que son importantes para nuestras comunidades. No importa cuál sea el problema que estamos resolviendo, si realmente creemos que es importante, debemos pensar en la solución de más alto impacto recursos que tengamos  disponibles.

## Trabajamos abiertamente

Dependemos en gran medida de las tecnologías y datos de código abierto para ejecutar nuestra misión. Como tal, abogamos por el uso y la contribución a proyectos de código, estándares e iniciativas de datos abiertos. Por ende, nuestros proyectos e iniciativas se ejecutan abiertamente. Creemos que para crear una cultura de colaboración, confianza y sostenibilidad debemos ser abiertos y transparentes. Nuestras comunidades siempre deben sentirse cómodas para encontrar y decir la verdad.

## Iteramos

No existe solución que sea perfecta o lo suficientemente completa, el fracaso es parte de la aventura. La velocidad es importante y el tiempo es escaso, especialmente para  organizaciones impulsadas por voluntarios. La retroalimentación, la colaboración y el cambio cultural deben revisarse y se fortalecerán con el tiempo. En consecuencia, nuestros proyectos deben iterar continuamente. Trabajamos de manera ágil y realmente creemos que el progreso se logra con pequeñas victorias que se entregan de forma gradual. Aceptamos el fracaso. Consideramos que el fracaso es un momento de aprendizaje en el camino al éxito. Detener una iniciativa cuando es apropiado es saludable y alentado.

**Comment by froi** [comment]
Retroalimentación desde Twitter de parte de la Dra. Zayira Jordán Conde:

> Yo incluiría: 
>
> Eliminar la brecha. No podemos hacer ethics-free code. 
>
> Reconocer parcializaciones. 
> Produce código honesto y posiblemente menos discriminatorio.

![image](https://user-images.githubusercontent.com/1918027/87951792-06124100-ca77-11ea-89a6-f03b51e265ce.png)

**Comment by Cuperino** [comment]
Sugerencia, en lugar de decir "Nos esforzamos por construir productos, no publicar código" escribir "Nos esforzamos por construir soluciones, no publicar código". El término `producto` tiene una connotación comercial que por lo general preferimos evitar en la comunidad opensource y en lugar de preferimos usar `proyecto`. Esto se debe a que el producto suele ser hecho por un grupo para el consumo de otras personas mientras que el proyecto le pertenece al colectivo, o al menos todos pueden formar parte del proyecto, es más invitativo.

En este caso sugiero `solución` y no `proyecto` porque decir proyecto tiene una connotación similar a querer publicar código por publicar código, que es exactamente lo que se quiere evitar. 

Otra razón para evitar el producto es porque implica un fin comercial y, aunque un buen producto se asegura de satisfacer una necesidad, una buena solución no necesariamente hace un buen producto. Ya sea porque no existe un mercado de gente dispuesta a pagar, quizá aún no ha sido inventado, o porque la cantidad de esfuerzo que entre toda la comunidad se invierte no sería posible de manera costo efectiva si una sola parte se encargara del proyecto.

**Comment by froi** [comment]
Gracias por las sugerencias @Cuperino. Super validas.

**Comment by froi** [comment]
Mås retroalimentacion de Twitter:

![image](https://user-images.githubusercontent.com/1918027/89108180-618fe780-d404-11ea-8dc8-32d445fcbf84.png)

**Comment by albertico** [comment]
Actualizamos el valor **_"Pensamos en personas primero"_** de acuerdo al [comentario de la Dra. Zayira via twitter](https://github.com/Code4PuertoRico/Code4PR/issues/38#issuecomment-661089037):

**Comment by froi** [comment]
Gracias a tod@s por los comentarios y retrolimentacion. Estaremos cerrando este issue y modificando los valores.
