### ISSUE TITLE
Feedback on our values for Code for PR

### ISSUE THREAD

**Issue by froi** [Code4PuertoRico/Code4PR#39]
These values represent the Code 4 Puerto Rico community. We adhere to them and they serve as our guiding principles both in good and bad times. They are intended to help us make decisions as well as to remind ourselves of the team that we wish to be.

Our values describe who we are, how we work together and how we build products. They represent choices that are directly related to our mission. They determine how Code 4 Puerto Rico will pursue its purpose.

We will be accepting feedback until July 25, 2020.

# Our Values

## Everyone is welcome to participate

In order to design solutions that represent everyone, we must involve individuals from all professional backgrounds, creed, sexual orientation, gender identity and social level. Building technology solutions is not the sole work of developers. And no matter where you live or where you are, if you can virtually collaborate with our initiatives, that’s all you need to participate.

## We think of people first

~The best products and solutions aren’t created in a vacuum. We need empathy and curiosity to understand the problems, ideate solutions and test our hypothesis. We must avoid making assumptions and listen to the individuals involved as much as possible. Only then we will start creating solutions that really address people’s needs.~

The best products and solutions aren’t created in a vacuum. We need empathy and curiosity to understand the problems, ideate solutions and test our hypothesis. We must avoid making assumptions. We must listen to the individuals that are impacted by our solutions as much as possible to remove our prejudices. Only then we will start creating less discriminatory solutions that address people’s needs.

## We strive to build products, not push code

Thoughtful solutions are more than code. Our decision making is heavily influenced by regulation, people’s concerns and their needs. We’re not just pushing code, we’re solving people’s problems through product experiences. The more interdisciplinary and diverse the teams working on our initiatives are, the more inclusive our solutions will be.

## We must prioritize impact

We can only solve so many problems at once. And there will also be so many volunteers willing to contribute to any initiative. Things are built with a shelf-life in mind and that’s okay. In order to develop solutions that are sustainable, we must focus on the things that matter to our communities. No matter what the problem we are solving is, if we truly believe it’s important, we must think of the most impactful way to solve it with the means and resources available to us.

## We work in the open

We rely heavily on open source technologies and data to execute our mission. As such, we advocate for the use and contribution to open source projects, open standards and open data initiatives. We expect that our projects and initiatives are executed in the open. We believe that in order to create a culture of collaboration, trust and sustainability we must be open and transparent. Our communities should always feel comfortable finding and speaking the truth.

## We must iterate

No solution is perfect or comprehensive enough and failure is part of the journey. Speed matters and time is scarce, especially for any volunteer driven organization. Feedback, collaboration and culture change need to be revisited and will strengthen through time. Consequently, our projects must continually iterate. We work in an agile fashion and truly believe that progress is made of small wins that get delivered (happen) incrementally.

- ~Failure is OK~
- ~Is OK to stop~
- ~Failure is a learning step for future success.~

We welcome failure. To us, failure is a learning step for future success. Stopping an initiative when appropriate is healthy and encouraged.

**Comment by Cuperino** [comment]
My advice, instead of using "We strive to build products, not push code" use "We strive to build solutions, not push code". The term product has a commercial connotation which we rather avoid in the opensource community and instead choose to use `project`. A product is usually done by a group for other's consumption, meanwhile projects belong to the collective; or at least everyone could become a part of it. It's more inviting.

I suggest using solution instead of project because project's connotation is similar to that of wanting to push code for the sake of code, which is exactly what you're trying to avoid.

Another reason to avoid product is that it implies a commercial end. While a good product makes sure needs are satisfied, a good solution doesn't necessarily make a good product. It could be there are no paying customers, or perhaps the market hasn't been invented yet; it could also be the amount of effort invested by the community exceeds what any single party could provide by cost effective means if only they were developing the project.

**Comment by froi** [comment]
Thanks for the suggestion @Cuperino. Super valid.

**Comment by albertico** [comment]
We updated the value **_"We think of people first"_** with the following text based on [the feedback from Dra. Zayira on Twitter](https://github.com/Code4PuertoRico/Code4PR/issues/38#issuecomment-661089037):

> The best products and solutions aren’t created in a vacuum. We need empathy and curiosity to understand the problems, ideate solutions and test our hypothesis. We must avoid making assumptions. We must listen to the individuals that are impacted by our solutions as much as possible to remove our prejudices. Only then we will start creating less discriminatory solutions that address people’s needs.

**Comment by froi** [comment]
Thank you all for your comments and feedback. We will be taking all of then into account and modifying our values doc where appropriate.
