### ISSUE TITLE
Centralizar interacciones y feedback en un solo repo

### ISSUE THREAD

**Issue by froi** [Code4PuertoRico/Code4PR#46]
Para hacer nuestras interacciones internas y externas mas sencillas de navegar, queremo utilizar este repo (Code4PR) como el repo principal para todo. Esto significa que todo issue, feedback o interacción sobre repositorios admin y de documentacion se harian aqui.

Para lograr esto se necesitan hacer varias cosas

- [ ] Actualizar el README para apuntar a otras partes de la organizacion. Eg. Code of Conduct & Slack Policy.
- [ ] Crear issue templates para diferentes interacciones.
  - [ ] Feedback sobre CoC
  - [ ] Feedback sobre el Slack Policy
  - [ ] Ideas para proyecto nuevo
  - [ ] Ideas o feedback a un proyecto

**Comment by jpadilla** [comment]
We've discussed a bit more and agree that there should be a central/unified way for reporting questions / feedback about our CoC, Slack Policy, etc. The same goes for ideas/feedback/questions about any of our existing projects and initiatives, and ideas for new ones.

The current proposal is to do this via a form that we can have in our website. In the background we can create form submissions as Issues or Discussions in the _correct_ GitHub repository for some, or send an email to the brigade team, post to a Google Spreadsheet, etc. We'd then link to this form from CoC, Slack Policy, repositories, Slack, social media, etc.

**Comment by froi** [comment]
This issue conversation will remain locked in favor of the [discussion in the website repository](https://github.com/Code4PuertoRico/code4puertorico.github.io/discussions/3).
