### ISSUE TITLE
Grabar los Meet-Ups para referencia y transparencia de los temas discutidos.

### ISSUE THREAD

**Issue by LaysCurbelo** [Code4PuertoRico/Code4PR#64]
# Public Comments / Comentarios del Publicos

Entiendo puede ser beneficioso tener un repositiorio con los meet ups grabados para personas que interesen ver como es la interraccion, ponerse al día y tener un record los acuerdos establecidos. Permite transparencia, continiudad y hasta un registro historico de nuestros encuentros. 

## Issue de referencia / Reference issue

- #[numero del issue]

**Comment by jpadilla** [comment]
Discutimos la idea de grabar los Hack Nights y decidimos que por ahora no es algo que queremos hacer.

- Overhead: Añade un overhead al tooling que usamos para los meetups virtuales.
- Consent/Privacy: Necesitamos consent de todos los participantes para grabar video/audio.

Dicho eso, otro tipo de formato de evento(presentaciones, lightning talks, etc) creo que debemos de considerar grabar for sure.

Aunque no grabemos los Hack Nights, proponemos usar discussions para tomar notas y generar artefactos: Más acá -> https://github.com/Code4PuertoRico/Code4PR/discussions/73
